import type { CourseContentPack, SourceReference } from './types'
import { assertValidCourseContentPack } from './validation'

export const DEFAULT_ENTRY_PACK_ID = 'default-entry'
export const DEFAULT_ENTRY_CONTENT_VERSION = '2026-05-28'

function source(path: string, language: 'zh' | 'en' = 'zh'): SourceReference {
  const [chapterId, subChapterId, sectionId] = path.split('/')
  return {
    kind: 'static_tour',
    tourPath: `tour/${path}/index.${language}.mdx`,
    chapterId,
    subChapterId,
    sectionId,
    language,
  }
}

function codeSource(path: string, language: 'zh' | 'en' = 'zh'): SourceReference {
  return {
    ...source(path, language),
    tourPath: `tour/${path}/index.${language}.cj`,
  }
}

export const defaultEntryCourseContentPack = assertValidCourseContentPack({
  packId: DEFAULT_ENTRY_PACK_ID,
  contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
  generatedAt: '2026-05-28T00:00:00.000Z',
  concepts: [
    {
      conceptId: 'cj.program.main',
      title: { zh: '程序入口与 main', en: 'Program entry and main' },
      summary: { zh: '仓颉程序从 main 函数开始执行。', en: 'Cangjie programs start at main.' },
      blockIds: ['cj.program.main.heading', 'cj.program.main.shape', 'cj.program.main.example'],
      skillIds: ['cj.program.main.write-entry'],
    },
    {
      conceptId: 'cj.io.println',
      title: { zh: '标准输出 println', en: 'Standard output println' },
      summary: { zh: '用 println 把值写到标准输出。', en: 'Use println to write values to stdout.' },
      blockIds: ['cj.io.println.heading', 'cj.io.println.output'],
      skillIds: ['cj.io.println.print-value'],
    },
    {
      conceptId: 'cj.var.immutable',
      title: { zh: '不可变绑定 let', en: 'Immutable binding let' },
      summary: { zh: 'let 绑定初始化后不能重新赋值。', en: 'A let binding cannot be reassigned after initialization.' },
      blockIds: ['cj.var.immutable.heading', 'cj.var.immutable.rule', 'cj.var.immutable.example'],
      skillIds: ['cj.var.immutable.choose-let'],
    },
    {
      conceptId: 'cj.var.mutable',
      title: { zh: '可变绑定 var', en: 'Mutable binding var' },
      summary: { zh: 'var 绑定可以在后续代码中重新赋值。', en: 'A var binding can be reassigned later.' },
      blockIds: ['cj.var.mutable.heading', 'cj.var.mutable.rule', 'cj.var.mutable.compare'],
      skillIds: ['cj.var.mutable.update-state'],
    },
    {
      conceptId: 'cj.type.basic',
      title: { zh: '基本类型', en: 'Basic types' },
      summary: { zh: 'Int、Float、Bool、Rune、String 等内建类型与字面量。', en: 'Built-in types and literals such as Int, Float, Bool, Rune, and String.' },
      blockIds: ['cj.type.basic.heading', 'cj.type.basic.integer', 'cj.type.basic.example'],
      skillIds: ['cj.type.basic.identify-literals'],
    },
    {
      conceptId: 'cj.type.annotation',
      title: { zh: '类型标注', en: 'Type annotation' },
      summary: { zh: '`name: Type = value` 形式的显式类型标注。', en: 'Explicit type annotations use `name: Type = value`.' },
      blockIds: ['cj.type.annotation.heading', 'cj.type.annotation.rule'],
      skillIds: ['cj.type.annotation.write-explicit'],
    },
    {
      conceptId: 'cj.type.inference',
      title: { zh: '静态类型推断', en: 'Static type inference' },
      summary: { zh: '编译器根据初始化值推断绑定类型。', en: 'The compiler infers binding types from initializers.' },
      blockIds: ['cj.type.inference.heading', 'cj.type.inference.rule'],
      skillIds: ['cj.type.inference.use-initializer'],
    },
    {
      conceptId: 'cj.expr.arithmetic',
      title: { zh: '算术运算', en: 'Arithmetic operators' },
      summary: { zh: '使用 +、-、*、/、% 和 ** 计算数值。', en: 'Use +, -, *, /, %, and ** for numeric computation.' },
      blockIds: ['cj.expr.arithmetic.heading', 'cj.expr.arithmetic.rule', 'cj.expr.arithmetic.example'],
      skillIds: ['cj.expr.arithmetic.compute-expression'],
    },
    {
      conceptId: 'cj.expr.comparison',
      title: { zh: '比较运算', en: 'Comparison operators' },
      summary: { zh: '比较运算返回 Bool。', en: 'Comparison operators return Bool.' },
      blockIds: ['cj.expr.comparison.heading', 'cj.expr.comparison.rule'],
      skillIds: ['cj.expr.comparison.produce-bool'],
    },
    {
      conceptId: 'cj.control.if-expr',
      title: { zh: 'if 表达式', en: 'if expression' },
      summary: { zh: 'if/else 根据 Bool 条件选择分支，条件需要括号。', en: 'if/else chooses branches from a Bool condition, with parenthesized conditions.' },
      blockIds: ['cj.control.if-expr.heading', 'cj.control.if-expr.rule', 'cj.control.if-expr.example'],
      skillIds: ['cj.control.if-expr.branch-on-bool'],
    },
  ],
  blocks: [
    {
      blockId: 'cj.program.main.heading',
      conceptId: 'cj.program.main',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 0,
      content: { type: 'heading', text: '程序入口与 main', level: 2 },
      localizedContent: { en: { type: 'heading', text: 'Program entry and main', level: 2 } },
      sourceRefs: [source('01-welcome/01-intro/01')],
    },
    {
      blockId: 'cj.program.main.shape',
      conceptId: 'cj.program.main',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 1,
      content: { type: 'paragraph', body: '仓颉程序从顶层 `main()` 开始执行。和很多语言不同，仓颉的入口函数不需要 `func` 关键字。' },
      localizedContent: { en: { type: 'paragraph', body: 'A Cangjie program starts at the top-level `main()` block. Unlike many languages, the entry point does not use the `func` keyword.' } },
      sourceRefs: [source('01-welcome/01-intro/01')],
    },
    {
      blockId: 'cj.program.main.example',
      conceptId: 'cj.program.main',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 2,
      content: {
        type: 'code_example',
        title: '最小入口程序',
        language: 'cangjie',
        code: 'main() {\n    println("Hello")\n}',
      },
      localizedContent: {
        en: {
          type: 'code_example',
          title: 'Minimal entry program',
          language: 'cangjie',
          code: 'main() {\n    println("Hello")\n}',
        },
      },
      sourceRefs: [codeSource('01-welcome/01-intro/01')],
      runnable: { status: 'runnable' },
    },
    {
      blockId: 'cj.io.println.heading',
      conceptId: 'cj.io.println',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 0,
      content: { type: 'heading', text: '标准输出 println', level: 2 },
      localizedContent: { en: { type: 'heading', text: 'Standard output println', level: 2 } },
      sourceRefs: [source('01-welcome/01-intro/01')],
    },
    {
      blockId: 'cj.io.println.output',
      conceptId: 'cj.io.println',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 1,
      content: { type: 'paragraph', body: '`println(value)` 会把值写到标准输出。AI 课堂里的练习主要通过标准输出判断代码行为。' },
      localizedContent: { en: { type: 'paragraph', body: '`println(value)` writes a value to standard output. Exercises in AI Classroom usually judge code behavior through stdout.' } },
      sourceRefs: [source('01-welcome/01-intro/01')],
    },
    {
      blockId: 'cj.var.immutable.heading',
      conceptId: 'cj.var.immutable',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 0,
      content: { type: 'heading', text: '不可变绑定 let', level: 2 },
      localizedContent: { en: { type: 'heading', text: 'Immutable binding let', level: 2 } },
      sourceRefs: [source('02-basics/01-bindings/01')],
    },
    {
      blockId: 'cj.var.immutable.rule',
      conceptId: 'cj.var.immutable',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 1,
      content: { type: 'concept_card', conceptId: 'cj.var.immutable', title: 'let 的规则', body: '`let` 把名字和值绑定起来。初始化完成后，这个名字不能再指向新的值；默认优先使用 `let` 可以减少意外修改。' },
      localizedContent: { en: { type: 'concept_card', conceptId: 'cj.var.immutable', title: 'The rule for let', body: '`let` binds a name to a value. After initialization, that name cannot point to a new value. Prefer `let` by default to reduce accidental mutation.' } },
      sourceRefs: [source('02-basics/01-bindings/01')],
    },
    {
      blockId: 'cj.var.immutable.example',
      conceptId: 'cj.var.immutable',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 2,
      content: {
        type: 'code_example',
        title: 'let 绑定',
        language: 'cangjie',
        code: 'main() {\n    let name = "Cangjie"\n    println(name)\n}',
      },
      localizedContent: {
        en: {
          type: 'code_example',
          title: 'let binding',
          language: 'cangjie',
          code: 'main() {\n    let name = "Cangjie"\n    println(name)\n}',
        },
      },
      sourceRefs: [codeSource('02-basics/01-bindings/01')],
      runnable: { status: 'runnable' },
    },
    {
      blockId: 'cj.var.mutable.heading',
      conceptId: 'cj.var.mutable',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 0,
      content: { type: 'heading', text: '可变绑定 var', level: 2 },
      localizedContent: { en: { type: 'heading', text: 'Mutable binding var', level: 2 } },
      sourceRefs: [source('02-basics/01-bindings/02')],
    },
    {
      blockId: 'cj.var.mutable.rule',
      conceptId: 'cj.var.mutable',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 1,
      content: { type: 'paragraph', body: '`var` 声明的绑定可以重新赋值。只有当变量确实需要计数、累积或更新状态时才使用 `var`。' },
      localizedContent: { en: { type: 'paragraph', body: 'A binding declared with `var` can be reassigned. Use `var` only when the variable really needs to count, accumulate, or update state.' } },
      sourceRefs: [source('02-basics/01-bindings/02')],
    },
    {
      blockId: 'cj.var.mutable.compare',
      conceptId: 'cj.var.mutable',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 2,
      content: {
        type: 'compare',
        leftTitle: 'let',
        left: [{ type: 'text', text: '初始化后不能重新赋值，适合默认选择。' }],
        rightTitle: 'var',
        right: [{ type: 'text', text: '允许后续赋值，适合需要变化的状态。' }],
      },
      localizedContent: {
        en: {
          type: 'compare',
          leftTitle: 'let',
          left: [{ type: 'text', text: 'Cannot be reassigned after initialization, so it is a good default choice.' }],
          rightTitle: 'var',
          right: [{ type: 'text', text: 'Allows later reassignment, so it fits state that needs to change.' }],
        },
      },
      sourceRefs: [source('02-basics/01-bindings/02')],
    },
    {
      blockId: 'cj.type.basic.heading',
      conceptId: 'cj.type.basic',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 0,
      content: { type: 'heading', text: '基本类型', level: 2 },
      localizedContent: { en: { type: 'heading', text: 'Basic types', level: 2 } },
      sourceRefs: [source('02-basics/02-basic-types/01')],
    },
    {
      blockId: 'cj.type.basic.integer',
      conceptId: 'cj.type.basic',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 1,
      content: { type: 'paragraph', body: '仓颉内建整数、浮点数、布尔值、字符和字符串等基本类型。没有类型上下文时，整数字面量通常推断为 `Int64`。' },
      localizedContent: { en: { type: 'paragraph', body: 'Cangjie has built-in basic types such as integers, floating-point numbers, booleans, runes, and strings. Without type context, integer literals are usually inferred as `Int64`.' } },
      sourceRefs: [source('02-basics/02-basic-types/01')],
    },
    {
      blockId: 'cj.type.basic.example',
      conceptId: 'cj.type.basic',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 2,
      content: {
        type: 'code_example',
        title: '基本字面量',
        language: 'cangjie',
        code: 'main() {\n    let count = 42\n    let ok = true\n    let name = "Cangjie"\n    println("${count}, ${ok}, ${name}")\n}',
      },
      localizedContent: {
        en: {
          type: 'code_example',
          title: 'Basic literals',
          language: 'cangjie',
          code: 'main() {\n    let count = 42\n    let ok = true\n    let name = "Cangjie"\n    println("${count}, ${ok}, ${name}")\n}',
        },
      },
      sourceRefs: [codeSource('02-basics/02-basic-types/01')],
      runnable: { status: 'runnable' },
    },
    {
      blockId: 'cj.type.annotation.heading',
      conceptId: 'cj.type.annotation',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 0,
      content: { type: 'heading', text: '类型标注', level: 2 },
      localizedContent: { en: { type: 'heading', text: 'Type annotation', level: 2 } },
      sourceRefs: [source('02-basics/02-bindings-types/01')],
    },
    {
      blockId: 'cj.type.annotation.rule',
      conceptId: 'cj.type.annotation',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 1,
      content: { type: 'paragraph', body: '显式类型标注写在名字后面：`let count: Int64 = 42`。公开 API 或需要强调类型时，标注能让意图更清楚。' },
      localizedContent: { en: { type: 'paragraph', body: 'Explicit type annotations come after the name: `let count: Int64 = 42`. They make intent clearer in public APIs or when the type deserves emphasis.' } },
      sourceRefs: [source('02-basics/02-bindings-types/01')],
    },
    {
      blockId: 'cj.type.inference.heading',
      conceptId: 'cj.type.inference',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 0,
      content: { type: 'heading', text: '静态类型推断', level: 2 },
      localizedContent: { en: { type: 'heading', text: 'Static type inference', level: 2 } },
      sourceRefs: [source('02-basics/02-basic-types/01')],
    },
    {
      blockId: 'cj.type.inference.rule',
      conceptId: 'cj.type.inference',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 1,
      content: { type: 'callout', tone: 'note', title: '推断不是动态类型', body: '类型推断发生在编译期。`let x = 42` 省略的是标注，不是类型本身；之后不能把 `x` 当作其他类型使用。' },
      localizedContent: { en: { type: 'callout', tone: 'note', title: 'Inference is not dynamic typing', body: 'Type inference happens at compile time. `let x = 42` omits the annotation, not the type itself; you cannot later use `x` as a different type.' } },
      sourceRefs: [source('02-basics/02-basic-types/01')],
    },
    {
      blockId: 'cj.expr.arithmetic.heading',
      conceptId: 'cj.expr.arithmetic',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 0,
      content: { type: 'heading', text: '算术运算', level: 2 },
      localizedContent: { en: { type: 'heading', text: 'Arithmetic operators', level: 2 } },
      sourceRefs: [source('02-basics/03-operators/01')],
    },
    {
      blockId: 'cj.expr.arithmetic.rule',
      conceptId: 'cj.expr.arithmetic',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 1,
      content: { type: 'paragraph', body: '仓颉支持 `+`、`-`、`*`、`/`、`%` 和 `**`。整数除法会向零舍入，括号可以改变计算顺序。' },
      localizedContent: { en: { type: 'paragraph', body: 'Cangjie supports `+`, `-`, `*`, `/`, `%`, and `**`. Integer division rounds toward zero, and parentheses can change evaluation order.' } },
      sourceRefs: [source('02-basics/03-operators/01')],
    },
    {
      blockId: 'cj.expr.arithmetic.example',
      conceptId: 'cj.expr.arithmetic',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 2,
      content: {
        type: 'code_example',
        title: '计算表达式',
        language: 'cangjie',
        code: 'main() {\n    println(2 + 3 * 4)\n    println((2 + 3) * 4)\n}',
      },
      localizedContent: {
        en: {
          type: 'code_example',
          title: 'Compute expressions',
          language: 'cangjie',
          code: 'main() {\n    println(2 + 3 * 4)\n    println((2 + 3) * 4)\n}',
        },
      },
      sourceRefs: [codeSource('02-basics/03-operators/01')],
      runnable: { status: 'runnable' },
    },
    {
      blockId: 'cj.expr.comparison.heading',
      conceptId: 'cj.expr.comparison',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 0,
      content: { type: 'heading', text: '比较运算', level: 2 },
      localizedContent: { en: { type: 'heading', text: 'Comparison operators', level: 2 } },
      sourceRefs: [source('02-basics/03-operators/02')],
    },
    {
      blockId: 'cj.expr.comparison.rule',
      conceptId: 'cj.expr.comparison',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 1,
      content: { type: 'paragraph', body: '`==`、`!=`、`<`、`<=`、`>`、`>=` 的结果是 `Bool`，可以作为 `if` 条件。条件必须明确是布尔值。' },
      localizedContent: { en: { type: 'paragraph', body: 'The result of `==`, `!=`, `<`, `<=`, `>`, and `>=` is `Bool`, which can be used as an `if` condition. Conditions must clearly be boolean values.' } },
      sourceRefs: [source('02-basics/03-operators/02')],
    },
    {
      blockId: 'cj.control.if-expr.heading',
      conceptId: 'cj.control.if-expr',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 0,
      content: { type: 'heading', text: 'if 表达式', level: 2 },
      localizedContent: { en: { type: 'heading', text: 'if expression', level: 2 } },
      sourceRefs: [source('03-flow-control/01-conditions/01')],
    },
    {
      blockId: 'cj.control.if-expr.rule',
      conceptId: 'cj.control.if-expr',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 1,
      content: { type: 'callout', tone: 'warning', title: '条件必须加括号', body: '仓颉要求 `if (condition) { ... }`。不能写成 `if condition { ... }`，也不能把整数直接当条件。' },
      localizedContent: { en: { type: 'callout', tone: 'warning', title: 'Conditions require parentheses', body: 'Cangjie requires `if (condition) { ... }`. Do not write `if condition { ... }`, and do not use an integer directly as a condition.' } },
      sourceRefs: [source('03-flow-control/01-conditions/01')],
    },
    {
      blockId: 'cj.control.if-expr.example',
      conceptId: 'cj.control.if-expr',
      contentVersion: DEFAULT_ENTRY_CONTENT_VERSION,
      order: 2,
      content: {
        type: 'code_example',
        title: 'if 分支',
        language: 'cangjie',
        code: 'main() {\n    let score = 85\n    if (score >= 60) {\n        println("pass")\n    } else {\n        println("retry")\n    }\n}',
      },
      localizedContent: {
        en: {
          type: 'code_example',
          title: 'if branch',
          language: 'cangjie',
          code: 'main() {\n    let score = 85\n    if (score >= 60) {\n        println("pass")\n    } else {\n        println("retry")\n    }\n}',
        },
      },
      sourceRefs: [codeSource('03-flow-control/01-conditions/01')],
      runnable: { status: 'runnable' },
    },
  ],
  skills: [
    {
      skillId: 'cj.program.main.write-entry',
      conceptIds: ['cj.program.main'],
      title: { zh: '写入口函数', en: 'Write an entry function' },
      summary: { zh: '能写出包含 main() 的最小可运行程序。', en: 'Can write a minimal runnable program with main().' },
      evidenceCriteria: ['Creates a top-level main() block.', 'Places executable statements inside main().'],
    },
    {
      skillId: 'cj.io.println.print-value',
      conceptIds: ['cj.io.println'],
      title: { zh: '打印值', en: 'Print a value' },
      summary: { zh: '能用 println 输出字符串或表达式结果。', en: 'Can use println to output a string or expression result.' },
      evidenceCriteria: ['Calls println with the requested value.', 'Produces the expected stdout.'],
    },
    {
      skillId: 'cj.var.immutable.choose-let',
      conceptIds: ['cj.var.immutable'],
      title: { zh: '选择 let', en: 'Choose let' },
      summary: { zh: '能在不需要重新赋值时使用 let。', en: 'Can use let when reassignment is unnecessary.' },
      evidenceCriteria: ['Declares an immutable binding with let.', 'Reads the binding without reassigning it.'],
    },
    {
      skillId: 'cj.var.mutable.update-state',
      conceptIds: ['cj.var.mutable'],
      title: { zh: '更新状态', en: 'Update state' },
      summary: { zh: '能在需要变化时使用 var 并重新赋值。', en: 'Can use var and reassign it when state must change.' },
      evidenceCriteria: ['Declares a mutable binding with var.', 'Reassigns it with a value of the same type.'],
    },
    {
      skillId: 'cj.type.basic.identify-literals',
      conceptIds: ['cj.type.basic'],
      title: { zh: '识别字面量类型', en: 'Identify literal types' },
      summary: { zh: '能使用基本字面量并理解默认整数类型。', en: 'Can use basic literals and understand default integer type.' },
      evidenceCriteria: ['Uses integer, Bool, or String literals appropriately.', 'Prints literal-backed values correctly.'],
    },
    {
      skillId: 'cj.type.annotation.write-explicit',
      conceptIds: ['cj.type.annotation'],
      title: { zh: '写显式类型', en: 'Write explicit types' },
      summary: { zh: '能写出 `name: Type = value`。', en: 'Can write `name: Type = value`.' },
      evidenceCriteria: ['Places the type annotation after the binding name.', 'Uses a compatible initializer.'],
    },
    {
      skillId: 'cj.type.inference.use-initializer',
      conceptIds: ['cj.type.inference'],
      title: { zh: '利用初始化值推断类型', en: 'Use initializer inference' },
      summary: { zh: '能省略可推断的局部变量类型。', en: 'Can omit local variable types that are inferable.' },
      evidenceCriteria: ['Declares a binding without an explicit type when the initializer is clear.', 'Uses the inferred value consistently.'],
    },
    {
      skillId: 'cj.expr.arithmetic.compute-expression',
      conceptIds: ['cj.expr.arithmetic'],
      title: { zh: '计算算术表达式', en: 'Compute arithmetic expressions' },
      summary: { zh: '能组合算术运算符并打印结果。', en: 'Can combine arithmetic operators and print the result.' },
      evidenceCriteria: ['Uses arithmetic operators in the requested order.', 'Produces the expected numeric stdout.'],
    },
    {
      skillId: 'cj.expr.comparison.produce-bool',
      conceptIds: ['cj.expr.comparison'],
      title: { zh: '产生 Bool 结果', en: 'Produce Bool results' },
      summary: { zh: '能用比较运算得到布尔值。', en: 'Can use comparison operators to produce Bool.' },
      evidenceCriteria: ['Uses a comparison operator.', 'Uses or prints the Bool result correctly.'],
    },
    {
      skillId: 'cj.control.if-expr.branch-on-bool',
      conceptIds: ['cj.control.if-expr'],
      title: { zh: '按 Bool 分支', en: 'Branch on Bool' },
      summary: { zh: '能写出带括号条件和 else 分支的 if。', en: 'Can write an if with a parenthesized condition and else branch.' },
      evidenceCriteria: ['Wraps the condition in parentheses.', 'Uses comparison output as the condition.'],
    },
  ],
  exerciseTemplates: [
    {
      templateId: 'cj.program.main.write-entry.hello',
      templateVersion: '1',
      skillId: 'cj.program.main.write-entry',
      conceptIds: ['cj.program.main'],
      title: { zh: '写 main', en: 'Write main' },
      prompt: { zh: '补全一个最小程序，让它输出 Hello。', en: 'Complete a minimal program that prints Hello.' },
      starterCode: '// TODO: write main\n',
      expectedOutput: 'Hello',
      matchMode: 'exact',
      intent: 'mainline',
      difficulty: 1,
      sourceRefs: [source('01-welcome/01-intro/01')],
    },
    {
      templateId: 'cj.io.println.print-value.cangjie',
      templateVersion: '1',
      skillId: 'cj.io.println.print-value',
      conceptIds: ['cj.io.println'],
      title: { zh: '打印 Cangjie', en: 'Print Cangjie' },
      prompt: { zh: '在 main 中用 println 输出 Cangjie。', en: 'Use println in main to print Cangjie.' },
      starterCode: 'main() {\n    // TODO\n}',
      expectedOutput: 'Cangjie',
      matchMode: 'exact',
      intent: 'mainline',
      difficulty: 1,
      sourceRefs: [source('01-welcome/01-intro/01')],
    },
    {
      templateId: 'cj.var.immutable.choose-let.answer',
      templateVersion: '1',
      skillId: 'cj.var.immutable.choose-let',
      conceptIds: ['cj.var.immutable'],
      title: { zh: '不可变答案', en: 'Immutable answer' },
      prompt: { zh: '用 let 声明 answer 为 42，并打印 answer。', en: 'Declare answer as 42 with let and print answer.' },
      starterCode: 'main() {\n    // TODO\n}',
      expectedOutput: '42',
      matchMode: 'exact',
      intent: 'mainline',
      difficulty: 1,
      sourceRefs: [source('02-basics/01-bindings/01')],
    },
    {
      templateId: 'cj.var.mutable.update-state.counter',
      templateVersion: '1',
      skillId: 'cj.var.mutable.update-state',
      conceptIds: ['cj.var.mutable'],
      title: { zh: '更新计数器', en: 'Update a counter' },
      prompt: { zh: '用 var 声明 count 为 1，将它加 2 后打印。', en: 'Declare count as 1 with var, add 2, then print it.' },
      starterCode: 'main() {\n    // TODO\n}',
      expectedOutput: '3',
      matchMode: 'exact',
      intent: 'mainline',
      difficulty: 1,
      sourceRefs: [source('02-basics/01-bindings/02')],
    },
    {
      templateId: 'cj.type.basic.identify-literals.bool',
      templateVersion: '1',
      skillId: 'cj.type.basic.identify-literals',
      conceptIds: ['cj.type.basic'],
      title: { zh: '打印布尔值', en: 'Print a Bool' },
      prompt: { zh: '声明 ok 为 true 并打印它。', en: 'Declare ok as true and print it.' },
      starterCode: 'main() {\n    // TODO\n}',
      expectedOutput: 'true',
      matchMode: 'exact',
      intent: 'mainline',
      difficulty: 1,
      sourceRefs: [source('02-basics/02-basic-types/01')],
    },
    {
      templateId: 'cj.type.annotation.write-explicit.int64',
      templateVersion: '1',
      skillId: 'cj.type.annotation.write-explicit',
      conceptIds: ['cj.type.annotation'],
      title: { zh: '显式 Int64', en: 'Explicit Int64' },
      prompt: { zh: '用显式类型 Int64 声明 year 为 2024，并打印。', en: 'Declare year as 2024 with explicit Int64 and print it.' },
      starterCode: 'main() {\n    // TODO\n}',
      expectedOutput: '2024',
      matchMode: 'exact',
      intent: 'mainline',
      difficulty: 2,
      sourceRefs: [source('02-basics/02-bindings-types/01')],
    },
    {
      templateId: 'cj.type.inference.use-initializer.name',
      templateVersion: '1',
      skillId: 'cj.type.inference.use-initializer',
      conceptIds: ['cj.type.inference'],
      title: { zh: '省略可推断类型', en: 'Omit an inferred type' },
      prompt: { zh: '不写类型标注，声明 name 为 "cj" 并打印。', en: 'Declare name as "cj" without a type annotation and print it.' },
      starterCode: 'main() {\n    // TODO\n}',
      expectedOutput: 'cj',
      matchMode: 'exact',
      intent: 'mainline',
      difficulty: 2,
      sourceRefs: [source('02-basics/02-basic-types/01')],
    },
    {
      templateId: 'cj.expr.arithmetic.compute-expression.precedence',
      templateVersion: '1',
      skillId: 'cj.expr.arithmetic.compute-expression',
      conceptIds: ['cj.expr.arithmetic'],
      title: { zh: '计算优先级', en: 'Compute precedence' },
      prompt: { zh: '打印 2 + 3 * 4 的结果。', en: 'Print the result of 2 + 3 * 4.' },
      starterCode: 'main() {\n    // TODO\n}',
      expectedOutput: '14',
      matchMode: 'exact',
      intent: 'mainline',
      difficulty: 1,
      sourceRefs: [source('02-basics/03-operators/01')],
    },
    {
      templateId: 'cj.expr.comparison.produce-bool.gte',
      templateVersion: '1',
      skillId: 'cj.expr.comparison.produce-bool',
      conceptIds: ['cj.expr.comparison'],
      title: { zh: '比较结果', en: 'Comparison result' },
      prompt: { zh: '打印 7 >= 3 的比较结果。', en: 'Print the result of 7 >= 3.' },
      starterCode: 'main() {\n    // TODO\n}',
      expectedOutput: 'true',
      matchMode: 'exact',
      intent: 'mainline',
      difficulty: 1,
      sourceRefs: [source('02-basics/03-operators/02')],
    },
    {
      templateId: 'cj.control.if-expr.branch-on-bool.pass',
      templateVersion: '1',
      skillId: 'cj.control.if-expr.branch-on-bool',
      conceptIds: ['cj.control.if-expr'],
      title: { zh: '及格分支', en: 'Pass branch' },
      prompt: { zh: '令 score 为 85。用 if 判断 score >= 60，成立时输出 pass，否则输出 retry。', en: 'Set score to 85. Use if to print pass when score >= 60, otherwise retry.' },
      starterCode: 'main() {\n    let score = 85\n    // TODO\n}',
      expectedOutput: 'pass',
      matchMode: 'exact',
      intent: 'mainline',
      difficulty: 2,
      sourceRefs: [source('03-flow-control/01-conditions/01')],
    },
  ],
  tracks: [
    {
      trackId: 'default-entry',
      title: { zh: 'AI 入门路径', en: 'AI entry track' },
      conceptIds: [
        'cj.program.main',
        'cj.io.println',
        'cj.var.immutable',
        'cj.var.mutable',
        'cj.type.basic',
        'cj.type.annotation',
        'cj.type.inference',
        'cj.expr.arithmetic',
        'cj.expr.comparison',
        'cj.control.if-expr',
      ],
      skillIds: [
        'cj.program.main.write-entry',
        'cj.io.println.print-value',
        'cj.var.immutable.choose-let',
        'cj.var.mutable.update-state',
        'cj.type.basic.identify-literals',
        'cj.type.annotation.write-explicit',
        'cj.type.inference.use-initializer',
        'cj.expr.arithmetic.compute-expression',
        'cj.expr.comparison.produce-bool',
        'cj.control.if-expr.branch-on-bool',
      ],
    },
  ],
} satisfies CourseContentPack)
