export const aiClassroomStyles = {
  layout: {
    root: 'ai-classroom-root h-screen',
    shell: 'flex h-full min-h-0 bg-[#FAF7F2] text-[#1F1B16]',
    main: 'flex min-w-0 flex-1 flex-col',
    viewport: 'min-h-0 flex-1 overflow-auto',
    content: 'mx-auto w-full max-w-[920px] px-6 py-8 pb-20',
    sectionIntro: 'mb-6 border-b border-[#E8E2D5] pb-5',
    sidebar: 'flex h-full w-[390px] shrink-0 flex-col border-l border-[#E8E2D5] bg-white shadow-[-12px_0_32px_rgba(31,27,22,.12)]',
    sidebarBody: 'min-h-0 flex-1',
  },
  header: {
    root: 'ai-classroom-header flex h-12 shrink-0 items-center justify-between border-b border-[#E8E2D5] bg-white px-5',
    content: 'flex min-w-0 items-center gap-3',
    brandMark: 'flex size-6 items-center justify-center rounded-md bg-[#0F8C6E] font-mono text-xs font-bold text-white',
    title: 'truncate text-sm font-semibold',
    subtitle: 'truncate text-xs text-[#8A8174]',
    sidebarHeader: 'ai-classroom-header flex h-12 shrink-0 items-center justify-between border-b border-[#E8E2D5] px-4',
  },
  text: {
    eyebrow: 'text-xs font-semibold uppercase text-[#0A6E57]',
    pageTitle: 'mt-1 text-2xl font-bold tracking-normal',
    heading: 'text-xl font-bold tracking-normal',
    body: 'text-sm leading-7',
    paragraph: 'text-[15px] leading-7',
    label: 'text-sm font-semibold',
    titleSmall: 'font-semibold',
    muted: 'text-xs text-[#8A8174]',
    warning: 'text-xs text-[#B47A12]',
    status: 'text-xs font-semibold text-[#0A6E57]',
  },
  surface: {
    base: 'ai-classroom-surface rounded-md border border-[#E8E2D5] bg-white',
    muted: 'ai-classroom-surface rounded-md border border-[#E8E2D5] bg-white px-4 py-4 text-sm text-[#8A8174]',
    card: 'ai-classroom-surface rounded-md border border-[#E8E2D5] bg-white p-4',
    accent: 'ai-classroom-surface ai-classroom-surface-accent overflow-hidden rounded-md border border-[#0F8C6E] bg-white',
    success: 'ai-classroom-surface ai-classroom-surface-success inline-flex items-center gap-2 rounded-md border border-[#BFE6D6] bg-[#F2FAF7] px-3 py-2 text-sm text-[#0A6E57]',
    warning: 'ai-classroom-surface ai-classroom-surface-warning rounded-md border border-[#F0D6A6] bg-[#FFF8E8] p-3 text-sm text-[#8A5A00]',
    system: 'ai-classroom-surface rounded-md border border-[#E8E2D5] bg-white p-3 text-xs text-[#8A8174]',
  },
  code: {
    inline: 'rounded bg-[#F4F1EB] px-1 font-mono text-[0.95em]',
    block: 'overflow-auto rounded-md border border-[#E8E2D5] bg-[#FBF8F2] p-4 font-mono text-sm',
    result: 'whitespace-pre-wrap rounded bg-[#F4F1EB] p-3 font-mono text-xs',
  },
  button: {
    primary: 'ai-classroom-button inline-flex items-center gap-2 rounded-md bg-[#0F8C6E] px-4 py-2 text-sm font-semibold text-white disabled:bg-[#BDB6AA]',
    secondary: 'ai-classroom-button inline-flex items-center gap-2 rounded-md border border-[#D9D2C2] bg-white px-3 py-1.5 text-xs font-medium text-[#5C5448] hover:bg-[#F4F1EB] disabled:opacity-50',
    secondaryLarge: 'ai-classroom-button inline-flex items-center gap-2 rounded-md border border-[#D9D2C2] px-4 py-2 text-sm text-[#5C5448] disabled:opacity-50',
    icon: 'ai-classroom-button inline-flex size-8 items-center justify-center rounded-md text-[#5C5448] hover:bg-[#F4F1EB]',
    warning: 'ai-classroom-button rounded-md border border-[#E5C16D] bg-white px-3 py-1.5 text-xs font-semibold text-[#7A4B00]',
  },
  badge: {
    phase: 'ai-classroom-badge rounded border border-[#E8E2D5] px-2 py-0.5 font-mono text-[11px] text-[#5C5448]',
    status: 'ai-classroom-badge shrink-0 text-xs font-semibold text-[#0A6E57]',
  },
  stream: {
    list: 'space-y-5',
    lessonBlocks: 'space-y-4',
    twoColumn: 'grid gap-3 sm:grid-cols-2',
    steps: 'list-decimal space-y-2 pl-5',
  },
  quiz: {
    header: 'flex items-center justify-between border-b border-[#E8E2D5] bg-[#F2FAF7] px-4 py-3',
    body: 'space-y-4 p-4',
    expectedFrame: 'rounded-md border border-[#E8E2D5]',
    expectedBar: 'border-b border-[#E8E2D5] bg-[#F4F1EB] px-3 py-2 text-xs text-[#5C5448]',
    editor: 'h-[420px]',
    actions: 'flex items-center gap-2',
  },
  progress: {
    root: 'ai-classroom-surface mt-5 overflow-hidden rounded-md border border-[#E8E2D5] bg-white text-sm',
    trigger: 'ai-classroom-disclosure flex w-full items-center justify-between gap-3 px-3 py-2 text-left hover:bg-[#F8F4ED]',
    triggerContent: 'flex min-w-0 items-center gap-2',
    chevron: 'size-4 shrink-0 text-[#8A8174] transition-transform',
    spinner: 'size-3.5 shrink-0 animate-spin text-[#0F8C6E]',
    title: 'font-semibold text-[#1F1B16]',
    status: 'shrink-0 text-xs text-[#8A8174]',
    body: 'border-t border-[#E8E2D5] bg-[#FBF8F2] p-3',
    pre: 'max-h-44 overflow-auto whitespace-pre-wrap break-words font-mono text-xs leading-5 text-[#5C5448]',
  },
} as const

export const classroomProgressStyles = aiClassroomStyles.progress
